politics:
	cnn_1: "https://edition.cnn.com/2020/02/03/politics/trump-senate-impeachment-trial-iowa-caucuses/index.html"
	cnn_2: "https://edition.cnn.com/2020/02/03/politics/senate-impeachment-trial-closing-arguments/index.html"
	cnn_3: "https://edition.cnn.com/interactive/2020/politics/hamburg-iowa-flood-2020-election/"
	cnn_4: "https://edition.cnn.com/2020/02/01/politics/impeachment-senate-floor-phone-call-trump/index.html"
	cnn_5: "https://edition.cnn.com/2020/02/02/politics/facebook-democrats-disinformation-iowa/index.html"
	bbc_1: "https://www.bbc.com/news/world-asia-china-51353279"
	bbc_2: "https://www.bbc.com/news/world-middle-east-51356626"
	bbc_3: "https://www.bbc.com/news/world-middle-east-51309126"
	bbc_4: "https://www.bbc.com/news/entertainment-arts-51355206"
	bbc_5: "https://www.bbc.com/news/health-51361955"
science:
	aaas_1: "https://www.sciencemag.org/news/2020/01/mining-coronavirus-genomes-clues-outbreak-s-origins"
	aaas_2: "https://www.sciencemag.org/news/2020/02/another-hiv-vaccine-strategy-fails-large-scale-study"
	aaas_3: "https://www.sciencemag.org/news/2020/01/spider-biologist-denies-suspicions-widespread-data-fraud-his-animal-personality"
	aaas_4: "https://www.sciencemag.org/news/2020/01/top-stories-doggerland-s-lost-world-star-swallowing-black-holes-and-engineering-killer"
	aaas_5: "https://www.sciencemag.org/news/2020/01/people-need-see-big-patterns-us-ecological-observatory-s-new-science-chief-looks-ahead"
	sa_1: "https://www.scientificamerican.com/article/orangutans-are-hanging-on-in-the-same-palm-oil-plantations-that-displace-them/"
	sa_2: "https://www.scientificamerican.com/article/experts-warn-of-possible-sustained-global-spread-of-new-coronavirus/"
	sa_3: "https://www.scientificamerican.com/article/study-reports-first-case-of-coronavirus-spread-by-asymptomatic-person/"
	sa_4: "https://blogs.scientificamerican.com/observations/have-we-solved-the-black-hole-information-paradox/"
	sa_5: "https://www.scientificamerican.com/article/home-star-stunner-best-ever-images-of-solar-surface-herald-new-era1/"
tech:
	wired_1: "https://www.wired.co.uk/article/marvel-baftas-bojack-netflix"
	wired_2: "https://www.wired.co.uk/article/brexit-twitter"
	wired_3: "https://www.wired.co.uk/article/e-scooters-london"
	wired_4: "https://www.wired.co.uk/article/trello-privacy"
	wired_5: "https://www.wired.co.uk/article/smart-home-technology-tracking"
	verge_1: "https://www.theverge.com/2020/2/3/21119915/microsoft-surface-hub-2x-cancel-major-software-update-features-release-date"
	verge_2: "https://www.theverge.com/2020/2/3/21119992/google-photos-monthly-printing-subscription-service-trial-price"
	verge_3: "https://www.theverge.com/2020/2/3/21117306/iowa-caucus-rural-broadband-access-election-campaign-sanders-warren"
	verge_4: "https://www.theverge.com/2020/2/3/21120107/tcl-blackberry-ends-phone-global-rights-date-2020"
	verge_5: "https://www.theverge.com/2020/2/3/21119932/airbnb-scams-vice-report-bait-and-switch-repair-costs-5-star-reviews-verification-program"
sport:
	bbc_s_1: "https://www.bbc.com/sport/golf/51354315"
	bbc_s_2: "https://www.bbc.com/sport/football/51253149"
	bbc_s_3: "https://www.bbc.com/sport/football/51349057"
	bbc_s_4: "https://www.bbc.com/sport/football/51355201"
	bbc_s_5: "https://www.bbc.com/sport/cricket/51281677"
	eusport_1: "https://www.eurosport.co.uk/cycling/cycling-news-astana-respond-to-jakob-fuglsang-and-michele-ferrari-claims_sto7650635/story.shtml"
	eusport_2: "https://www.eurosport.co.uk/cricket/hungry-morgan-sets-sights-on-t20-world-cup-success-for-england_sto7650640/story.shtml"
	eusport_3: "https://www.eurosport.co.uk/football/premier-league/2019-2020/football-news-no-hard-feelings-says-spurs-alli-on-sterling-s-mistimed-tackle_sto7650734/story.shtml"
	eusport_4: "https://www.eurosport.co.uk/tennis/australian-open/2020/tennis-news-when-could-novak-djokovic-surpass-roger-federer-and-win-no.21_sto7650593/story.shtml"
	eusport_5: "https://www.eurosport.co.uk/football/morata-injury-leaves-atletico-short-on-forwards_sto7650744/story.shtml"
life:
	ind_1: "https://www.independent.co.uk/news/long_reads/white-noise-sleep-apps-technology-soothing-insomnia-a8709266.html"
	ind_2: "https://www.independent.co.uk/independentpremium/new-york-notebook-life-in-new-york-international-woman-a9253571.html"
	ind_3: "https://www.independent.co.uk/voices/gardening-house-plants-millennials-social-media-housing-market-a8869271.html"
	ind_4: "https://www.independent.co.uk/life-style/british-tea-time-stress-uk-workers-study-a8756641.html"
	ind_5: "https://www.independent.co.uk/life-style/design/how-to-update-home-decor-new-year-bathroom-kitchen-bedroom-january-a8709111.html"
	vogue_1: "https://www.vogue.co.uk/arts-and-lifestyle/article/bafta-2020-diversity-row"
	vogue_2: "https://www.vogue.co.uk/article/baftas"
	vogue_3: "https://www.vogue.co.uk/arts-and-lifestyle/article/cheer-netflix"
	vogue_4: "https://www.vogue.co.uk/arts-and-lifestyle/article/oscar-nominated-films-netflix"
	vogue_5: "https://www.vogue.co.uk/arts-and-lifestyle/gallery/things-to-do-in-toronto"